# Generated by Django 4.2.23 on 2025-08-16 15:56

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motdmessage",
            name="show_to_all",
            field=models.BooleanField(
                default=True, help_text="Show to all members (users with Member state)"
            ),
        ),
        migrations.AlterField(
            model_name="motdmessage",
            name="style",
            field=models.CharField(
                choices=[
                    ("info", "Low Priority"),
                    ("success", "Medium Priority"),
                    ("warning", "High Priority"),
                    ("danger", "Important"),
                ],
                default="info",
                help_text="Message priority level",
                max_length=10,
            ),
        ),
    ]
