# Generated by Django 4.2.23 on 2025-08-16 17:16

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0024_alter_userprofile_language"),
        ("motd", "0002_alter_motdmessage_show_to_all_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access this app, Motd."),
                    ("manage_access", "Can manage Motd."),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.RemoveField(
            model_name="groupmotd",
            name="group",
        ),
        migrations.DeleteModel(
            name="StateMotd",
        ),
        migrations.AlterModelOptions(
            name="motdmessage",
            options={
                "default_permissions": (),
                "ordering": ["-start_date"],
                "verbose_name": "MOTD Message",
                "verbose_name_plural": "MOTD Messages",
            },
        ),
        migrations.RemoveField(
            model_name="motdmessage",
            name="show_to_all",
        ),
        migrations.AddField(
            model_name="motdmessage",
            name="restricted_to_states",
            field=models.ManyToManyField(
                blank=True,
                help_text="If specified, only show to users in these states",
                to="authentication.state",
            ),
        ),
        migrations.DeleteModel(
            name="GroupMotd",
        ),
    ]
